### ISSUE TITLE
Fix spore burst chance to hold

### ISSUE THREAD

**Issue by jfaubert087** [OpenMeridian/Meridian59#1075]
Don't anyone find current spore burst chance to hold is too OP? Fix it please. (Enhancement)

**Comment by skittles1** [comment]
100% chance to hold, min duration 5 seconds... it likely does need looking at.

**Comment by jfaubert087** [comment]
How about temporariy disabling the spell until justification about it? It's generaly unfair at this moment.

**Comment by skittles1** [comment]
The spell requires two schools to buy and the effect (the sporeburst cloud) is stationary. I don't think disabling the spell is warranted.

**Comment by skittles1** [comment]
Fixed #1316
