### ISSUE TITLE
game time outs when i zone

### ISSUE THREAD

**Issue by NiNjAz** [OpenMeridian/Meridian59#379]
Been having this issue on and off last couple days where my game just times out when i zone thru w door or open area..any type of zoning.  When i goto zone, my character zones to the new map so it looks normal on other players screens but on my screen im still in the previous map and chat is frozen and spell castin etc.

I log off n log back on real quick and im in fhe new zone and can keep playing.  Its getting worse n worse and similar stuff has been happening now when i dont zone at all, just lags out.  Anyone else experiencing this?

**Comment by skittles1** [comment]
Closing, these are likely latency issues (and haven't been able to reproduce any or see them live).
